### ISSUE TITLE
.env file is being tracked

### ISSUE THREAD

**Issue by ndzamboni** [ndzamboni/Potty_Partner#7]
Having a bug where the .env file isn't being ignored in the gitignore. Tried to fix it but was unsuccessful.

**Comment by contra19** [comment]
.env file was not downloaded after merging fixes in to main. @TristinRohr @ndzamboni please try again before we close out this issue to verify.

**Comment by ndzamboni** [comment]
Looks like the problem is resolved for me. I'm closing out the issue.
